{{- if .Values.envRenderSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-env
  namespace: {{ template "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.envRenderSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end }}
