apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ template "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  API_KEY: {{ .Values.API_KEY | b64enc | quote }}
