{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- $root := . }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml . | indent 4) $root }}
{{- end }}
  name: {{ template "app.serviceAccountName" . }}
  namespace: {{ template "app.namespace" . }}
{{- end }}
